#!/bin/bash
gam create group "all-teachers@schoolgus.ukr.education" name "Всі вчителі" description "Загальна група для всіх педагогів"
gam create group "all-students@schoolgus.ukr.education" name "Всі учні" description "Загальна група для всіх здобувачів освіти"
gam create group "students-1-4@schoolgus.ukr.education" name "Учні 1-4 класів" description "Початкова школа (1-4 класи)"
gam create group "students-5-9@schoolgus.ukr.education" name "Учні 5-9 класів" description "Середня школа (5-9 класи)"
gam create group "students-10-11@schoolgus.ukr.education" name "Учні 10-11 класів" description "Старша школа (10-11 класи)"
gam create group "if-1@schoolgus.ukr.education" name "Індивідуальне навчання 1 клас" description "Індивідуальна форма навчання (Педагогічний патронаж/Сімейна)"
gam create group "if-2@schoolgus.ukr.education" name "Індивідуальне навчання 2 клас" description "Індивідуальна форма навчання (Педагогічний патронаж/Сімейна)"
gam create group "if-3@schoolgus.ukr.education" name "Індивідуальне навчання 3 клас" description "Індивідуальна форма навчання (Педагогічний патронаж/Сімейна)"
gam create group "if-4@schoolgus.ukr.education" name "Індивідуальне навчання 4 клас" description "Індивідуальна форма навчання (Педагогічний патронаж/Сімейна)"
gam create group "if-5@schoolgus.ukr.education" name "Індивідуальне навчання 5 клас" description "Індивідуальна форма навчання (Педагогічний патронаж/Сімейна)"
gam create group "if-6@schoolgus.ukr.education" name "Індивідуальне навчання 6 клас" description "Індивідуальна форма навчання (Педагогічний патронаж/Сімейна)"
gam create group "if-7@schoolgus.ukr.education" name "Індивідуальне навчання 7 клас" description "Індивідуальна форма навчання (Педагогічний патронаж/Сімейна)"
gam create group "if-8@schoolgus.ukr.education" name "Індивідуальне навчання 8 клас" description "Індивідуальна форма навчання (Педагогічний патронаж/Сімейна)"
gam create group "if-9@schoolgus.ukr.education" name "Індивідуальне навчання 9 клас" description "Індивідуальна форма навчання (Педагогічний патронаж/Сімейна)"
gam create group "if-10@schoolgus.ukr.education" name "Індивідуальне навчання 10 клас" description "Індивідуальна форма навчання (Педагогічний патронаж/Сімейна)"
gam create group "if-11@schoolgus.ukr.education" name "Індивідуальне навчання 11 клас" description "Індивідуальна форма навчання (Педагогічний патронаж/Сімейна)"
gam create group "class-1-a-ukr-g1@schoolgus.ukr.education" name "1-А клас Українська мова (1 група)" description "Підгрупа МОН"
gam create group "class-1-a-ukr-g2@schoolgus.ukr.education" name "1-А клас Українська мова (2 група)" description "Підгрупа МОН"
gam create group "class-1-a-eng-g1@schoolgus.ukr.education" name "1-А клас Англійська мова (1 група)" description "Підгрупа МОН"
gam create group "class-1-a-eng-g2@schoolgus.ukr.education" name "1-А клас Англійська мова (2 група)" description "Підгрупа МОН"
gam create group "class-1-a-info-g1@schoolgus.ukr.education" name "1-А клас Інформатика (1 група)" description "Підгрупа МОН"
gam create group "class-1-a-info-g2@schoolgus.ukr.education" name "1-А клас Інформатика (2 група)" description "Підгрупа МОН"
gam create group "class-1-a-tech-g1@schoolgus.ukr.education" name "1-А клас Трудове навчання (1 група)" description "Підгрупа МОН"
gam create group "class-1-a-tech-g2@schoolgus.ukr.education" name "1-А клас Трудове навчання (2 група)" description "Підгрупа МОН"
gam create group "class-1-b-ukr-g1@schoolgus.ukr.education" name "1-Б клас Українська мова (1 група)" description "Підгрупа МОН"
gam create group "class-1-b-ukr-g2@schoolgus.ukr.education" name "1-Б клас Українська мова (2 група)" description "Підгрупа МОН"
gam create group "class-1-b-eng-g1@schoolgus.ukr.education" name "1-Б клас Англійська мова (1 група)" description "Підгрупа МОН"
gam create group "class-1-b-eng-g2@schoolgus.ukr.education" name "1-Б клас Англійська мова (2 група)" description "Підгрупа МОН"
gam create group "class-1-b-info-g1@schoolgus.ukr.education" name "1-Б клас Інформатика (1 група)" description "Підгрупа МОН"
gam create group "class-1-b-info-g2@schoolgus.ukr.education" name "1-Б клас Інформатика (2 група)" description "Підгрупа МОН"
gam create group "class-1-b-tech-g1@schoolgus.ukr.education" name "1-Б клас Трудове навчання (1 група)" description "Підгрупа МОН"
gam create group "class-1-b-tech-g2@schoolgus.ukr.education" name "1-Б клас Трудове навчання (2 група)" description "Підгрупа МОН"
gam create group "class-1-v-ukr-g1@schoolgus.ukr.education" name "1-В клас Українська мова (1 група)" description "Підгрупа МОН"
gam create group "class-1-v-ukr-g2@schoolgus.ukr.education" name "1-В клас Українська мова (2 група)" description "Підгрупа МОН"
gam create group "class-1-v-eng-g1@schoolgus.ukr.education" name "1-В клас Англійська мова (1 група)" description "Підгрупа МОН"
gam create group "class-1-v-eng-g2@schoolgus.ukr.education" name "1-В клас Англійська мова (2 група)" description "Підгрупа МОН"
gam create group "class-1-v-info-g1@schoolgus.ukr.education" name "1-В клас Інформатика (1 група)" description "Підгрупа МОН"
gam create group "class-1-v-info-g2@schoolgus.ukr.education" name "1-В клас Інформатика (2 група)" description "Підгрупа МОН"
gam create group "class-1-v-tech-g1@schoolgus.ukr.education" name "1-В клас Трудове навчання (1 група)" description "Підгрупа МОН"
gam create group "class-1-v-tech-g2@schoolgus.ukr.education" name "1-В клас Трудове навчання (2 група)" description "Підгрупа МОН"
gam create group "class-1-g-ukr-g1@schoolgus.ukr.education" name "1-Г клас Українська мова (1 група)" description "Підгрупа МОН"
gam create group "class-1-g-ukr-g2@schoolgus.ukr.education" name "1-Г клас Українська мова (2 група)" description "Підгрупа МОН"
gam create group "class-1-g-eng-g1@schoolgus.ukr.education" name "1-Г клас Англійська мова (1 група)" description "Підгрупа МОН"
gam create group "class-1-g-eng-g2@schoolgus.ukr.education" name "1-Г клас Англійська мова (2 група)" description "Підгрупа МОН"
gam create group "class-1-g-info-g1@schoolgus.ukr.education" name "1-Г клас Інформатика (1 група)" description "Підгрупа МОН"
gam create group "class-1-g-info-g2@schoolgus.ukr.education" name "1-Г клас Інформатика (2 група)" description "Підгрупа МОН"
gam create group "class-1-g-tech-g1@schoolgus.ukr.education" name "1-Г клас Трудове навчання (1 група)" description "Підгрупа МОН"
gam create group "class-1-g-tech-g2@schoolgus.ukr.education" name "1-Г клас Трудове навчання (2 група)" description "Підгрупа МОН"
gam create group "class-2-a-ukr-g1@schoolgus.ukr.education" name "2-А клас Українська мова (1 група)" description "Підгрупа МОН"
gam create group "class-2-a-ukr-g2@schoolgus.ukr.education" name "2-А клас Українська мова (2 група)" description "Підгрупа МОН"
gam create group "class-2-a-eng-g1@schoolgus.ukr.education" name "2-А клас Англійська мова (1 група)" description "Підгрупа МОН"
gam create group "class-2-a-eng-g2@schoolgus.ukr.education" name "2-А клас Англійська мова (2 група)" description "Підгрупа МОН"
gam create group "class-2-a-info-g1@schoolgus.ukr.education" name "2-А клас Інформатика (1 група)" description "Підгрупа МОН"
gam create group "class-2-a-info-g2@schoolgus.ukr.education" name "2-А клас Інформатика (2 група)" description "Підгрупа МОН"
gam create group "class-2-a-tech-g1@schoolgus.ukr.education" name "2-А клас Трудове навчання (1 група)" description "Підгрупа МОН"
gam create group "class-2-a-tech-g2@schoolgus.ukr.education" name "2-А клас Трудове навчання (2 група)" description "Підгрупа МОН"
gam create group "class-2-b-ukr-g1@schoolgus.ukr.education" name "2-Б клас Українська мова (1 група)" description "Підгрупа МОН"
gam create group "class-2-b-ukr-g2@schoolgus.ukr.education" name "2-Б клас Українська мова (2 група)" description "Підгрупа МОН"
gam create group "class-2-b-eng-g1@schoolgus.ukr.education" name "2-Б клас Англійська мова (1 група)" description "Підгрупа МОН"
gam create group "class-2-b-eng-g2@schoolgus.ukr.education" name "2-Б клас Англійська мова (2 група)" description "Підгрупа МОН"
gam create group "class-2-b-info-g1@schoolgus.ukr.education" name "2-Б клас Інформатика (1 група)" description "Підгрупа МОН"
gam create group "class-2-b-info-g2@schoolgus.ukr.education" name "2-Б клас Інформатика (2 група)" description "Підгрупа МОН"
gam create group "class-2-b-tech-g1@schoolgus.ukr.education" name "2-Б клас Трудове навчання (1 група)" description "Підгрупа МОН"
gam create group "class-2-b-tech-g2@schoolgus.ukr.education" name "2-Б клас Трудове навчання (2 група)" description "Підгрупа МОН"
gam create group "class-2-v-ukr-g1@schoolgus.ukr.education" name "2-В клас Українська мова (1 група)" description "Підгрупа МОН"
gam create group "class-2-v-ukr-g2@schoolgus.ukr.education" name "2-В клас Українська мова (2 група)" description "Підгрупа МОН"
gam create group "class-2-v-eng-g1@schoolgus.ukr.education" name "2-В клас Англійська мова (1 група)" description "Підгрупа МОН"
gam create group "class-2-v-eng-g2@schoolgus.ukr.education" name "2-В клас Англійська мова (2 група)" description "Підгрупа МОН"
gam create group "class-2-v-info-g1@schoolgus.ukr.education" name "2-В клас Інформатика (1 група)" description "Підгрупа МОН"
gam create group "class-2-v-info-g2@schoolgus.ukr.education" name "2-В клас Інформатика (2 група)" description "Підгрупа МОН"
gam create group "class-2-v-tech-g1@schoolgus.ukr.education" name "2-В клас Трудове навчання (1 група)" description "Підгрупа МОН"
gam create group "class-2-v-tech-g2@schoolgus.ukr.education" name "2-В клас Трудове навчання (2 група)" description "Підгрупа МОН"
gam create group "class-2-g-ukr-g1@schoolgus.ukr.education" name "2-Г клас Українська мова (1 група)" description "Підгрупа МОН"
gam create group "class-2-g-ukr-g2@schoolgus.ukr.education" name "2-Г клас Українська мова (2 група)" description "Підгрупа МОН"
gam create group "class-2-g-eng-g1@schoolgus.ukr.education" name "2-Г клас Англійська мова (1 група)" description "Підгрупа МОН"
gam create group "class-2-g-eng-g2@schoolgus.ukr.education" name "2-Г клас Англійська мова (2 група)" description "Підгрупа МОН"
gam create group "class-2-g-info-g1@schoolgus.ukr.education" name "2-Г клас Інформатика (1 група)" description "Підгрупа МОН"
gam create group "class-2-g-info-g2@schoolgus.ukr.education" name "2-Г клас Інформатика (2 група)" description "Підгрупа МОН"
gam create group "class-2-g-tech-g1@schoolgus.ukr.education" name "2-Г клас Трудове навчання (1 група)" description "Підгрупа МОН"
gam create group "class-2-g-tech-g2@schoolgus.ukr.education" name "2-Г клас Трудове навчання (2 група)" description "Підгрупа МОН"
gam create group "class-3-a-ukr-g1@schoolgus.ukr.education" name "3-А клас Українська мова (1 група)" description "Підгрупа МОН"
gam create group "class-3-a-ukr-g2@schoolgus.ukr.education" name "3-А клас Українська мова (2 група)" description "Підгрупа МОН"
gam create group "class-3-a-eng-g1@schoolgus.ukr.education" name "3-А клас Англійська мова (1 група)" description "Підгрупа МОН"
gam create group "class-3-a-eng-g2@schoolgus.ukr.education" name "3-А клас Англійська мова (2 група)" description "Підгрупа МОН"
gam create group "class-3-a-info-g1@schoolgus.ukr.education" name "3-А клас Інформатика (1 група)" description "Підгрупа МОН"
gam create group "class-3-a-info-g2@schoolgus.ukr.education" name "3-А клас Інформатика (2 група)" description "Підгрупа МОН"
gam create group "class-3-a-tech-g1@schoolgus.ukr.education" name "3-А клас Трудове навчання (1 група)" description "Підгрупа МОН"
gam create group "class-3-a-tech-g2@schoolgus.ukr.education" name "3-А клас Трудове навчання (2 група)" description "Підгрупа МОН"
gam create group "class-3-b-ukr-g1@schoolgus.ukr.education" name "3-Б клас Українська мова (1 група)" description "Підгрупа МОН"
gam create group "class-3-b-ukr-g2@schoolgus.ukr.education" name "3-Б клас Українська мова (2 група)" description "Підгрупа МОН"
gam create group "class-3-b-eng-g1@schoolgus.ukr.education" name "3-Б клас Англійська мова (1 група)" description "Підгрупа МОН"
gam create group "class-3-b-eng-g2@schoolgus.ukr.education" name "3-Б клас Англійська мова (2 група)" description "Підгрупа МОН"
gam create group "class-3-b-info-g1@schoolgus.ukr.education" name "3-Б клас Інформатика (1 група)" description "Підгрупа МОН"
gam create group "class-3-b-info-g2@schoolgus.ukr.education" name "3-Б клас Інформатика (2 група)" description "Підгрупа МОН"
gam create group "class-3-b-tech-g1@schoolgus.ukr.education" name "3-Б клас Трудове навчання (1 група)" description "Підгрупа МОН"
gam create group "class-3-b-tech-g2@schoolgus.ukr.education" name "3-Б клас Трудове навчання (2 група)" description "Підгрупа МОН"
gam create group "class-3-v-ukr-g1@schoolgus.ukr.education" name "3-В клас Українська мова (1 група)" description "Підгрупа МОН"
gam create group "class-3-v-ukr-g2@schoolgus.ukr.education" name "3-В клас Українська мова (2 група)" description "Підгрупа МОН"
gam create group "class-3-v-eng-g1@schoolgus.ukr.education" name "3-В клас Англійська мова (1 група)" description "Підгрупа МОН"
gam create group "class-3-v-eng-g2@schoolgus.ukr.education" name "3-В клас Англійська мова (2 група)" description "Підгрупа МОН"
gam create group "class-3-v-info-g1@schoolgus.ukr.education" name "3-В клас Інформатика (1 група)" description "Підгрупа МОН"
gam create group "class-3-v-info-g2@schoolgus.ukr.education" name "3-В клас Інформатика (2 група)" description "Підгрупа МОН"
gam create group "class-3-v-tech-g1@schoolgus.ukr.education" name "3-В клас Трудове навчання (1 група)" description "Підгрупа МОН"
gam create group "class-3-v-tech-g2@schoolgus.ukr.education" name "3-В клас Трудове навчання (2 група)" description "Підгрупа МОН"
gam create group "class-3-g-ukr-g1@schoolgus.ukr.education" name "3-Г клас Українська мова (1 група)" description "Підгрупа МОН"
gam create group "class-3-g-ukr-g2@schoolgus.ukr.education" name "3-Г клас Українська мова (2 група)" description "Підгрупа МОН"
gam create group "class-3-g-eng-g1@schoolgus.ukr.education" name "3-Г клас Англійська мова (1 група)" description "Підгрупа МОН"
gam create group "class-3-g-eng-g2@schoolgus.ukr.education" name "3-Г клас Англійська мова (2 група)" description "Підгрупа МОН"
gam create group "class-3-g-info-g1@schoolgus.ukr.education" name "3-Г клас Інформатика (1 група)" description "Підгрупа МОН"
gam create group "class-3-g-info-g2@schoolgus.ukr.education" name "3-Г клас Інформатика (2 група)" description "Підгрупа МОН"
gam create group "class-3-g-tech-g1@schoolgus.ukr.education" name "3-Г клас Трудове навчання (1 група)" description "Підгрупа МОН"
gam create group "class-3-g-tech-g2@schoolgus.ukr.education" name "3-Г клас Трудове навчання (2 група)" description "Підгрупа МОН"
gam create group "class-4-a-ukr-g1@schoolgus.ukr.education" name "4-А клас Українська мова (1 група)" description "Підгрупа МОН"
gam create group "class-4-a-ukr-g2@schoolgus.ukr.education" name "4-А клас Українська мова (2 група)" description "Підгрупа МОН"
gam create group "class-4-a-eng-g1@schoolgus.ukr.education" name "4-А клас Англійська мова (1 група)" description "Підгрупа МОН"
gam create group "class-4-a-eng-g2@schoolgus.ukr.education" name "4-А клас Англійська мова (2 група)" description "Підгрупа МОН"
gam create group "class-4-a-info-g1@schoolgus.ukr.education" name "4-А клас Інформатика (1 група)" description "Підгрупа МОН"
gam create group "class-4-a-info-g2@schoolgus.ukr.education" name "4-А клас Інформатика (2 група)" description "Підгрупа МОН"
gam create group "class-4-a-tech-g1@schoolgus.ukr.education" name "4-А клас Трудове навчання (1 група)" description "Підгрупа МОН"
gam create group "class-4-a-tech-g2@schoolgus.ukr.education" name "4-А клас Трудове навчання (2 група)" description "Підгрупа МОН"
gam create group "class-4-b-ukr-g1@schoolgus.ukr.education" name "4-Б клас Українська мова (1 група)" description "Підгрупа МОН"
gam create group "class-4-b-ukr-g2@schoolgus.ukr.education" name "4-Б клас Українська мова (2 група)" description "Підгрупа МОН"
gam create group "class-4-b-eng-g1@schoolgus.ukr.education" name "4-Б клас Англійська мова (1 група)" description "Підгрупа МОН"
gam create group "class-4-b-eng-g2@schoolgus.ukr.education" name "4-Б клас Англійська мова (2 група)" description "Підгрупа МОН"
gam create group "class-4-b-info-g1@schoolgus.ukr.education" name "4-Б клас Інформатика (1 група)" description "Підгрупа МОН"
gam create group "class-4-b-info-g2@schoolgus.ukr.education" name "4-Б клас Інформатика (2 група)" description "Підгрупа МОН"
gam create group "class-4-b-tech-g1@schoolgus.ukr.education" name "4-Б клас Трудове навчання (1 група)" description "Підгрупа МОН"
gam create group "class-4-b-tech-g2@schoolgus.ukr.education" name "4-Б клас Трудове навчання (2 група)" description "Підгрупа МОН"
gam create group "class-4-v-ukr-g1@schoolgus.ukr.education" name "4-В клас Українська мова (1 група)" description "Підгрупа МОН"
gam create group "class-4-v-ukr-g2@schoolgus.ukr.education" name "4-В клас Українська мова (2 група)" description "Підгрупа МОН"
gam create group "class-4-v-eng-g1@schoolgus.ukr.education" name "4-В клас Англійська мова (1 група)" description "Підгрупа МОН"
gam create group "class-4-v-eng-g2@schoolgus.ukr.education" name "4-В клас Англійська мова (2 група)" description "Підгрупа МОН"
gam create group "class-4-v-info-g1@schoolgus.ukr.education" name "4-В клас Інформатика (1 група)" description "Підгрупа МОН"
gam create group "class-4-v-info-g2@schoolgus.ukr.education" name "4-В клас Інформатика (2 група)" description "Підгрупа МОН"
gam create group "class-4-v-tech-g1@schoolgus.ukr.education" name "4-В клас Трудове навчання (1 група)" description "Підгрупа МОН"
gam create group "class-4-v-tech-g2@schoolgus.ukr.education" name "4-В клас Трудове навчання (2 група)" description "Підгрупа МОН"
gam create group "class-4-g-ukr-g1@schoolgus.ukr.education" name "4-Г клас Українська мова (1 група)" description "Підгрупа МОН"
gam create group "class-4-g-ukr-g2@schoolgus.ukr.education" name "4-Г клас Українська мова (2 група)" description "Підгрупа МОН"
gam create group "class-4-g-eng-g1@schoolgus.ukr.education" name "4-Г клас Англійська мова (1 група)" description "Підгрупа МОН"
gam create group "class-4-g-eng-g2@schoolgus.ukr.education" name "4-Г клас Англійська мова (2 група)" description "Підгрупа МОН"
gam create group "class-4-g-info-g1@schoolgus.ukr.education" name "4-Г клас Інформатика (1 група)" description "Підгрупа МОН"
gam create group "class-4-g-info-g2@schoolgus.ukr.education" name "4-Г клас Інформатика (2 група)" description "Підгрупа МОН"
gam create group "class-4-g-tech-g1@schoolgus.ukr.education" name "4-Г клас Трудове навчання (1 група)" description "Підгрупа МОН"
gam create group "class-4-g-tech-g2@schoolgus.ukr.education" name "4-Г клас Трудове навчання (2 група)" description "Підгрупа МОН"
gam create group "class-5-a-ukr-g1@schoolgus.ukr.education" name "5-А клас Українська мова (1 група)" description "Підгрупа МОН"
gam create group "class-5-a-ukr-g2@schoolgus.ukr.education" name "5-А клас Українська мова (2 група)" description "Підгрупа МОН"
gam create group "class-5-a-eng-g1@schoolgus.ukr.education" name "5-А клас Англійська мова (1 група)" description "Підгрупа МОН"
gam create group "class-5-a-eng-g2@schoolgus.ukr.education" name "5-А клас Англійська мова (2 група)" description "Підгрупа МОН"
gam create group "class-5-a-info-g1@schoolgus.ukr.education" name "5-А клас Інформатика (1 група)" description "Підгрупа МОН"
gam create group "class-5-a-info-g2@schoolgus.ukr.education" name "5-А клас Інформатика (2 група)" description "Підгрупа МОН"
gam create group "class-5-a-tech-g1@schoolgus.ukr.education" name "5-А клас Трудове навчання (1 група)" description "Підгрупа МОН"
gam create group "class-5-a-tech-g2@schoolgus.ukr.education" name "5-А клас Трудове навчання (2 група)" description "Підгрупа МОН"
gam create group "class-5-b-ukr-g1@schoolgus.ukr.education" name "5-Б клас Українська мова (1 група)" description "Підгрупа МОН"
gam create group "class-5-b-ukr-g2@schoolgus.ukr.education" name "5-Б клас Українська мова (2 група)" description "Підгрупа МОН"
gam create group "class-5-b-eng-g1@schoolgus.ukr.education" name "5-Б клас Англійська мова (1 група)" description "Підгрупа МОН"
gam create group "class-5-b-eng-g2@schoolgus.ukr.education" name "5-Б клас Англійська мова (2 група)" description "Підгрупа МОН"
gam create group "class-5-b-info-g1@schoolgus.ukr.education" name "5-Б клас Інформатика (1 група)" description "Підгрупа МОН"
gam create group "class-5-b-info-g2@schoolgus.ukr.education" name "5-Б клас Інформатика (2 група)" description "Підгрупа МОН"
gam create group "class-5-b-tech-g1@schoolgus.ukr.education" name "5-Б клас Трудове навчання (1 група)" description "Підгрупа МОН"
gam create group "class-5-b-tech-g2@schoolgus.ukr.education" name "5-Б клас Трудове навчання (2 група)" description "Підгрупа МОН"
gam create group "class-5-v-ukr-g1@schoolgus.ukr.education" name "5-В клас Українська мова (1 група)" description "Підгрупа МОН"
gam create group "class-5-v-ukr-g2@schoolgus.ukr.education" name "5-В клас Українська мова (2 група)" description "Підгрупа МОН"
gam create group "class-5-v-eng-g1@schoolgus.ukr.education" name "5-В клас Англійська мова (1 група)" description "Підгрупа МОН"
gam create group "class-5-v-eng-g2@schoolgus.ukr.education" name "5-В клас Англійська мова (2 група)" description "Підгрупа МОН"
gam create group "class-5-v-info-g1@schoolgus.ukr.education" name "5-В клас Інформатика (1 група)" description "Підгрупа МОН"
gam create group "class-5-v-info-g2@schoolgus.ukr.education" name "5-В клас Інформатика (2 група)" description "Підгрупа МОН"
gam create group "class-5-v-tech-g1@schoolgus.ukr.education" name "5-В клас Трудове навчання (1 група)" description "Підгрупа МОН"
gam create group "class-5-v-tech-g2@schoolgus.ukr.education" name "5-В клас Трудове навчання (2 група)" description "Підгрупа МОН"
gam create group "class-5-g-ukr-g1@schoolgus.ukr.education" name "5-Г клас Українська мова (1 група)" description "Підгрупа МОН"
gam create group "class-5-g-ukr-g2@schoolgus.ukr.education" name "5-Г клас Українська мова (2 група)" description "Підгрупа МОН"
gam create group "class-5-g-eng-g1@schoolgus.ukr.education" name "5-Г клас Англійська мова (1 група)" description "Підгрупа МОН"
gam create group "class-5-g-eng-g2@schoolgus.ukr.education" name "5-Г клас Англійська мова (2 група)" description "Підгрупа МОН"
gam create group "class-5-g-info-g1@schoolgus.ukr.education" name "5-Г клас Інформатика (1 група)" description "Підгрупа МОН"
gam create group "class-5-g-info-g2@schoolgus.ukr.education" name "5-Г клас Інформатика (2 група)" description "Підгрупа МОН"
gam create group "class-5-g-tech-g1@schoolgus.ukr.education" name "5-Г клас Трудове навчання (1 група)" description "Підгрупа МОН"
gam create group "class-5-g-tech-g2@schoolgus.ukr.education" name "5-Г клас Трудове навчання (2 група)" description "Підгрупа МОН"
gam create group "class-6-a-ukr-g1@schoolgus.ukr.education" name "6-А клас Українська мова (1 група)" description "Підгрупа МОН"
gam create group "class-6-a-ukr-g2@schoolgus.ukr.education" name "6-А клас Українська мова (2 група)" description "Підгрупа МОН"
gam create group "class-6-a-eng-g1@schoolgus.ukr.education" name "6-А клас Англійська мова (1 група)" description "Підгрупа МОН"
gam create group "class-6-a-eng-g2@schoolgus.ukr.education" name "6-А клас Англійська мова (2 група)" description "Підгрупа МОН"
gam create group "class-6-a-info-g1@schoolgus.ukr.education" name "6-А клас Інформатика (1 група)" description "Підгрупа МОН"
gam create group "class-6-a-info-g2@schoolgus.ukr.education" name "6-А клас Інформатика (2 група)" description "Підгрупа МОН"
gam create group "class-6-a-tech-g1@schoolgus.ukr.education" name "6-А клас Трудове навчання (1 група)" description "Підгрупа МОН"
gam create group "class-6-a-tech-g2@schoolgus.ukr.education" name "6-А клас Трудове навчання (2 група)" description "Підгрупа МОН"
gam create group "class-6-b-ukr-g1@schoolgus.ukr.education" name "6-Б клас Українська мова (1 група)" description "Підгрупа МОН"
gam create group "class-6-b-ukr-g2@schoolgus.ukr.education" name "6-Б клас Українська мова (2 група)" description "Підгрупа МОН"
gam create group "class-6-b-eng-g1@schoolgus.ukr.education" name "6-Б клас Англійська мова (1 група)" description "Підгрупа МОН"
gam create group "class-6-b-eng-g2@schoolgus.ukr.education" name "6-Б клас Англійська мова (2 група)" description "Підгрупа МОН"
gam create group "class-6-b-info-g1@schoolgus.ukr.education" name "6-Б клас Інформатика (1 група)" description "Підгрупа МОН"
gam create group "class-6-b-info-g2@schoolgus.ukr.education" name "6-Б клас Інформатика (2 група)" description "Підгрупа МОН"
gam create group "class-6-b-tech-g1@schoolgus.ukr.education" name "6-Б клас Трудове навчання (1 група)" description "Підгрупа МОН"
gam create group "class-6-b-tech-g2@schoolgus.ukr.education" name "6-Б клас Трудове навчання (2 група)" description "Підгрупа МОН"
gam create group "class-6-v-ukr-g1@schoolgus.ukr.education" name "6-В клас Українська мова (1 група)" description "Підгрупа МОН"
gam create group "class-6-v-ukr-g2@schoolgus.ukr.education" name "6-В клас Українська мова (2 група)" description "Підгрупа МОН"
gam create group "class-6-v-eng-g1@schoolgus.ukr.education" name "6-В клас Англійська мова (1 група)" description "Підгрупа МОН"
gam create group "class-6-v-eng-g2@schoolgus.ukr.education" name "6-В клас Англійська мова (2 група)" description "Підгрупа МОН"
gam create group "class-6-v-info-g1@schoolgus.ukr.education" name "6-В клас Інформатика (1 група)" description "Підгрупа МОН"
gam create group "class-6-v-info-g2@schoolgus.ukr.education" name "6-В клас Інформатика (2 група)" description "Підгрупа МОН"
gam create group "class-6-v-tech-g1@schoolgus.ukr.education" name "6-В клас Трудове навчання (1 група)" description "Підгрупа МОН"
gam create group "class-6-v-tech-g2@schoolgus.ukr.education" name "6-В клас Трудове навчання (2 група)" description "Підгрупа МОН"
gam create group "class-6-g-ukr-g1@schoolgus.ukr.education" name "6-Г клас Українська мова (1 група)" description "Підгрупа МОН"
gam create group "class-6-g-ukr-g2@schoolgus.ukr.education" name "6-Г клас Українська мова (2 група)" description "Підгрупа МОН"
gam create group "class-6-g-eng-g1@schoolgus.ukr.education" name "6-Г клас Англійська мова (1 група)" description "Підгрупа МОН"
gam create group "class-6-g-eng-g2@schoolgus.ukr.education" name "6-Г клас Англійська мова (2 група)" description "Підгрупа МОН"
gam create group "class-6-g-info-g1@schoolgus.ukr.education" name "6-Г клас Інформатика (1 група)" description "Підгрупа МОН"
gam create group "class-6-g-info-g2@schoolgus.ukr.education" name "6-Г клас Інформатика (2 група)" description "Підгрупа МОН"
gam create group "class-6-g-tech-g1@schoolgus.ukr.education" name "6-Г клас Трудове навчання (1 група)" description "Підгрупа МОН"
gam create group "class-6-g-tech-g2@schoolgus.ukr.education" name "6-Г клас Трудове навчання (2 група)" description "Підгрупа МОН"
gam create group "class-7-a-ukr-g1@schoolgus.ukr.education" name "7-А клас Українська мова (1 група)" description "Підгрупа МОН"
gam create group "class-7-a-ukr-g2@schoolgus.ukr.education" name "7-А клас Українська мова (2 група)" description "Підгрупа МОН"
gam create group "class-7-a-eng-g1@schoolgus.ukr.education" name "7-А клас Англійська мова (1 група)" description "Підгрупа МОН"
gam create group "class-7-a-eng-g2@schoolgus.ukr.education" name "7-А клас Англійська мова (2 група)" description "Підгрупа МОН"
gam create group "class-7-a-info-g1@schoolgus.ukr.education" name "7-А клас Інформатика (1 група)" description "Підгрупа МОН"
gam create group "class-7-a-info-g2@schoolgus.ukr.education" name "7-А клас Інформатика (2 група)" description "Підгрупа МОН"
gam create group "class-7-a-tech-g1@schoolgus.ukr.education" name "7-А клас Трудове навчання (1 група)" description "Підгрупа МОН"
gam create group "class-7-a-tech-g2@schoolgus.ukr.education" name "7-А клас Трудове навчання (2 група)" description "Підгрупа МОН"
gam create group "class-7-b-ukr-g1@schoolgus.ukr.education" name "7-Б клас Українська мова (1 група)" description "Підгрупа МОН"
gam create group "class-7-b-ukr-g2@schoolgus.ukr.education" name "7-Б клас Українська мова (2 група)" description "Підгрупа МОН"
gam create group "class-7-b-eng-g1@schoolgus.ukr.education" name "7-Б клас Англійська мова (1 група)" description "Підгрупа МОН"
gam create group "class-7-b-eng-g2@schoolgus.ukr.education" name "7-Б клас Англійська мова (2 група)" description "Підгрупа МОН"
gam create group "class-7-b-info-g1@schoolgus.ukr.education" name "7-Б клас Інформатика (1 група)" description "Підгрупа МОН"
gam create group "class-7-b-info-g2@schoolgus.ukr.education" name "7-Б клас Інформатика (2 група)" description "Підгрупа МОН"
gam create group "class-7-b-tech-g1@schoolgus.ukr.education" name "7-Б клас Трудове навчання (1 група)" description "Підгрупа МОН"
gam create group "class-7-b-tech-g2@schoolgus.ukr.education" name "7-Б клас Трудове навчання (2 група)" description "Підгрупа МОН"
gam create group "class-7-v-ukr-g1@schoolgus.ukr.education" name "7-В клас Українська мова (1 група)" description "Підгрупа МОН"
gam create group "class-7-v-ukr-g2@schoolgus.ukr.education" name "7-В клас Українська мова (2 група)" description "Підгрупа МОН"
gam create group "class-7-v-eng-g1@schoolgus.ukr.education" name "7-В клас Англійська мова (1 група)" description "Підгрупа МОН"
gam create group "class-7-v-eng-g2@schoolgus.ukr.education" name "7-В клас Англійська мова (2 група)" description "Підгрупа МОН"
gam create group "class-7-v-info-g1@schoolgus.ukr.education" name "7-В клас Інформатика (1 група)" description "Підгрупа МОН"
gam create group "class-7-v-info-g2@schoolgus.ukr.education" name "7-В клас Інформатика (2 група)" description "Підгрупа МОН"
gam create group "class-7-v-tech-g1@schoolgus.ukr.education" name "7-В клас Трудове навчання (1 група)" description "Підгрупа МОН"
gam create group "class-7-v-tech-g2@schoolgus.ukr.education" name "7-В клас Трудове навчання (2 група)" description "Підгрупа МОН"
gam create group "class-7-g-ukr-g1@schoolgus.ukr.education" name "7-Г клас Українська мова (1 група)" description "Підгрупа МОН"
gam create group "class-7-g-ukr-g2@schoolgus.ukr.education" name "7-Г клас Українська мова (2 група)" description "Підгрупа МОН"
gam create group "class-7-g-eng-g1@schoolgus.ukr.education" name "7-Г клас Англійська мова (1 група)" description "Підгрупа МОН"
gam create group "class-7-g-eng-g2@schoolgus.ukr.education" name "7-Г клас Англійська мова (2 група)" description "Підгрупа МОН"
gam create group "class-7-g-info-g1@schoolgus.ukr.education" name "7-Г клас Інформатика (1 група)" description "Підгрупа МОН"
gam create group "class-7-g-info-g2@schoolgus.ukr.education" name "7-Г клас Інформатика (2 група)" description "Підгрупа МОН"
gam create group "class-7-g-tech-g1@schoolgus.ukr.education" name "7-Г клас Трудове навчання (1 група)" description "Підгрупа МОН"
gam create group "class-7-g-tech-g2@schoolgus.ukr.education" name "7-Г клас Трудове навчання (2 група)" description "Підгрупа МОН"
gam create group "class-8-a-ukr-g1@schoolgus.ukr.education" name "8-А клас Українська мова (1 група)" description "Підгрупа МОН"
gam create group "class-8-a-ukr-g2@schoolgus.ukr.education" name "8-А клас Українська мова (2 група)" description "Підгрупа МОН"
gam create group "class-8-a-eng-g1@schoolgus.ukr.education" name "8-А клас Англійська мова (1 група)" description "Підгрупа МОН"
gam create group "class-8-a-eng-g2@schoolgus.ukr.education" name "8-А клас Англійська мова (2 група)" description "Підгрупа МОН"
gam create group "class-8-a-info-g1@schoolgus.ukr.education" name "8-А клас Інформатика (1 група)" description "Підгрупа МОН"
gam create group "class-8-a-info-g2@schoolgus.ukr.education" name "8-А клас Інформатика (2 група)" description "Підгрупа МОН"
gam create group "class-8-a-tech-g1@schoolgus.ukr.education" name "8-А клас Трудове навчання (1 група)" description "Підгрупа МОН"
gam create group "class-8-a-tech-g2@schoolgus.ukr.education" name "8-А клас Трудове навчання (2 група)" description "Підгрупа МОН"
gam create group "class-8-b-ukr-g1@schoolgus.ukr.education" name "8-Б клас Українська мова (1 група)" description "Підгрупа МОН"
gam create group "class-8-b-ukr-g2@schoolgus.ukr.education" name "8-Б клас Українська мова (2 група)" description "Підгрупа МОН"
gam create group "class-8-b-eng-g1@schoolgus.ukr.education" name "8-Б клас Англійська мова (1 група)" description "Підгрупа МОН"
gam create group "class-8-b-eng-g2@schoolgus.ukr.education" name "8-Б клас Англійська мова (2 група)" description "Підгрупа МОН"
gam create group "class-8-b-info-g1@schoolgus.ukr.education" name "8-Б клас Інформатика (1 група)" description "Підгрупа МОН"
gam create group "class-8-b-info-g2@schoolgus.ukr.education" name "8-Б клас Інформатика (2 група)" description "Підгрупа МОН"
gam create group "class-8-b-tech-g1@schoolgus.ukr.education" name "8-Б клас Трудове навчання (1 група)" description "Підгрупа МОН"
gam create group "class-8-b-tech-g2@schoolgus.ukr.education" name "8-Б клас Трудове навчання (2 група)" description "Підгрупа МОН"
gam create group "class-8-v-ukr-g1@schoolgus.ukr.education" name "8-В клас Українська мова (1 група)" description "Підгрупа МОН"
gam create group "class-8-v-ukr-g2@schoolgus.ukr.education" name "8-В клас Українська мова (2 група)" description "Підгрупа МОН"
gam create group "class-8-v-eng-g1@schoolgus.ukr.education" name "8-В клас Англійська мова (1 група)" description "Підгрупа МОН"
gam create group "class-8-v-eng-g2@schoolgus.ukr.education" name "8-В клас Англійська мова (2 група)" description "Підгрупа МОН"
gam create group "class-8-v-info-g1@schoolgus.ukr.education" name "8-В клас Інформатика (1 група)" description "Підгрупа МОН"
gam create group "class-8-v-info-g2@schoolgus.ukr.education" name "8-В клас Інформатика (2 група)" description "Підгрупа МОН"
gam create group "class-8-v-tech-g1@schoolgus.ukr.education" name "8-В клас Трудове навчання (1 група)" description "Підгрупа МОН"
gam create group "class-8-v-tech-g2@schoolgus.ukr.education" name "8-В клас Трудове навчання (2 група)" description "Підгрупа МОН"
gam create group "class-8-g-ukr-g1@schoolgus.ukr.education" name "8-Г клас Українська мова (1 група)" description "Підгрупа МОН"
gam create group "class-8-g-ukr-g2@schoolgus.ukr.education" name "8-Г клас Українська мова (2 група)" description "Підгрупа МОН"
gam create group "class-8-g-eng-g1@schoolgus.ukr.education" name "8-Г клас Англійська мова (1 група)" description "Підгрупа МОН"
gam create group "class-8-g-eng-g2@schoolgus.ukr.education" name "8-Г клас Англійська мова (2 група)" description "Підгрупа МОН"
gam create group "class-8-g-info-g1@schoolgus.ukr.education" name "8-Г клас Інформатика (1 група)" description "Підгрупа МОН"
gam create group "class-8-g-info-g2@schoolgus.ukr.education" name "8-Г клас Інформатика (2 група)" description "Підгрупа МОН"
gam create group "class-8-g-tech-g1@schoolgus.ukr.education" name "8-Г клас Трудове навчання (1 група)" description "Підгрупа МОН"
gam create group "class-8-g-tech-g2@schoolgus.ukr.education" name "8-Г клас Трудове навчання (2 група)" description "Підгрупа МОН"
gam create group "class-9-a-ukr-g1@schoolgus.ukr.education" name "9-А клас Українська мова (1 група)" description "Підгрупа МОН"
gam create group "class-9-a-ukr-g2@schoolgus.ukr.education" name "9-А клас Українська мова (2 група)" description "Підгрупа МОН"
gam create group "class-9-a-eng-g1@schoolgus.ukr.education" name "9-А клас Англійська мова (1 група)" description "Підгрупа МОН"
gam create group "class-9-a-eng-g2@schoolgus.ukr.education" name "9-А клас Англійська мова (2 група)" description "Підгрупа МОН"
gam create group "class-9-a-info-g1@schoolgus.ukr.education" name "9-А клас Інформатика (1 група)" description "Підгрупа МОН"
gam create group "class-9-a-info-g2@schoolgus.ukr.education" name "9-А клас Інформатика (2 група)" description "Підгрупа МОН"
gam create group "class-9-a-tech-g1@schoolgus.ukr.education" name "9-А клас Трудове навчання (1 група)" description "Підгрупа МОН"
gam create group "class-9-a-tech-g2@schoolgus.ukr.education" name "9-А клас Трудове навчання (2 група)" description "Підгрупа МОН"
gam create group "class-9-b-ukr-g1@schoolgus.ukr.education" name "9-Б клас Українська мова (1 група)" description "Підгрупа МОН"
gam create group "class-9-b-ukr-g2@schoolgus.ukr.education" name "9-Б клас Українська мова (2 група)" description "Підгрупа МОН"
gam create group "class-9-b-eng-g1@schoolgus.ukr.education" name "9-Б клас Англійська мова (1 група)" description "Підгрупа МОН"
gam create group "class-9-b-eng-g2@schoolgus.ukr.education" name "9-Б клас Англійська мова (2 група)" description "Підгрупа МОН"
gam create group "class-9-b-info-g1@schoolgus.ukr.education" name "9-Б клас Інформатика (1 група)" description "Підгрупа МОН"
gam create group "class-9-b-info-g2@schoolgus.ukr.education" name "9-Б клас Інформатика (2 група)" description "Підгрупа МОН"
gam create group "class-9-b-tech-g1@schoolgus.ukr.education" name "9-Б клас Трудове навчання (1 група)" description "Підгрупа МОН"
gam create group "class-9-b-tech-g2@schoolgus.ukr.education" name "9-Б клас Трудове навчання (2 група)" description "Підгрупа МОН"
gam create group "class-9-v-ukr-g1@schoolgus.ukr.education" name "9-В клас Українська мова (1 група)" description "Підгрупа МОН"
gam create group "class-9-v-ukr-g2@schoolgus.ukr.education" name "9-В клас Українська мова (2 група)" description "Підгрупа МОН"
gam create group "class-9-v-eng-g1@schoolgus.ukr.education" name "9-В клас Англійська мова (1 група)" description "Підгрупа МОН"
gam create group "class-9-v-eng-g2@schoolgus.ukr.education" name "9-В клас Англійська мова (2 група)" description "Підгрупа МОН"
gam create group "class-9-v-info-g1@schoolgus.ukr.education" name "9-В клас Інформатика (1 група)" description "Підгрупа МОН"
gam create group "class-9-v-info-g2@schoolgus.ukr.education" name "9-В клас Інформатика (2 група)" description "Підгрупа МОН"
gam create group "class-9-v-tech-g1@schoolgus.ukr.education" name "9-В клас Трудове навчання (1 група)" description "Підгрупа МОН"
gam create group "class-9-v-tech-g2@schoolgus.ukr.education" name "9-В клас Трудове навчання (2 група)" description "Підгрупа МОН"
gam create group "class-9-g-ukr-g1@schoolgus.ukr.education" name "9-Г клас Українська мова (1 група)" description "Підгрупа МОН"
gam create group "class-9-g-ukr-g2@schoolgus.ukr.education" name "9-Г клас Українська мова (2 група)" description "Підгрупа МОН"
gam create group "class-9-g-eng-g1@schoolgus.ukr.education" name "9-Г клас Англійська мова (1 група)" description "Підгрупа МОН"
gam create group "class-9-g-eng-g2@schoolgus.ukr.education" name "9-Г клас Англійська мова (2 група)" description "Підгрупа МОН"
gam create group "class-9-g-info-g1@schoolgus.ukr.education" name "9-Г клас Інформатика (1 група)" description "Підгрупа МОН"
gam create group "class-9-g-info-g2@schoolgus.ukr.education" name "9-Г клас Інформатика (2 група)" description "Підгрупа МОН"
gam create group "class-9-g-tech-g1@schoolgus.ukr.education" name "9-Г клас Трудове навчання (1 група)" description "Підгрупа МОН"
gam create group "class-9-g-tech-g2@schoolgus.ukr.education" name "9-Г клас Трудове навчання (2 група)" description "Підгрупа МОН"
gam create group "class-10-a-ukr-g1@schoolgus.ukr.education" name "10-А клас Українська мова (1 група)" description "Підгрупа МОН"
gam create group "class-10-a-ukr-g2@schoolgus.ukr.education" name "10-А клас Українська мова (2 група)" description "Підгрупа МОН"
gam create group "class-10-a-eng-g1@schoolgus.ukr.education" name "10-А клас Англійська мова (1 група)" description "Підгрупа МОН"
gam create group "class-10-a-eng-g2@schoolgus.ukr.education" name "10-А клас Англійська мова (2 група)" description "Підгрупа МОН"
gam create group "class-10-a-info-g1@schoolgus.ukr.education" name "10-А клас Інформатика (1 група)" description "Підгрупа МОН"
gam create group "class-10-a-info-g2@schoolgus.ukr.education" name "10-А клас Інформатика (2 група)" description "Підгрупа МОН"
gam create group "class-10-a-tech-g1@schoolgus.ukr.education" name "10-А клас Трудове навчання (1 група)" description "Підгрупа МОН"
gam create group "class-10-a-tech-g2@schoolgus.ukr.education" name "10-А клас Трудове навчання (2 група)" description "Підгрупа МОН"
gam create group "class-10-b-ukr-g1@schoolgus.ukr.education" name "10-Б клас Українська мова (1 група)" description "Підгрупа МОН"
gam create group "class-10-b-ukr-g2@schoolgus.ukr.education" name "10-Б клас Українська мова (2 група)" description "Підгрупа МОН"
gam create group "class-10-b-eng-g1@schoolgus.ukr.education" name "10-Б клас Англійська мова (1 група)" description "Підгрупа МОН"
gam create group "class-10-b-eng-g2@schoolgus.ukr.education" name "10-Б клас Англійська мова (2 група)" description "Підгрупа МОН"
gam create group "class-10-b-info-g1@schoolgus.ukr.education" name "10-Б клас Інформатика (1 група)" description "Підгрупа МОН"
gam create group "class-10-b-info-g2@schoolgus.ukr.education" name "10-Б клас Інформатика (2 група)" description "Підгрупа МОН"
gam create group "class-10-b-tech-g1@schoolgus.ukr.education" name "10-Б клас Трудове навчання (1 група)" description "Підгрупа МОН"
gam create group "class-10-b-tech-g2@schoolgus.ukr.education" name "10-Б клас Трудове навчання (2 група)" description "Підгрупа МОН"
gam create group "class-10-v-ukr-g1@schoolgus.ukr.education" name "10-В клас Українська мова (1 група)" description "Підгрупа МОН"
gam create group "class-10-v-ukr-g2@schoolgus.ukr.education" name "10-В клас Українська мова (2 група)" description "Підгрупа МОН"
gam create group "class-10-v-eng-g1@schoolgus.ukr.education" name "10-В клас Англійська мова (1 група)" description "Підгрупа МОН"
gam create group "class-10-v-eng-g2@schoolgus.ukr.education" name "10-В клас Англійська мова (2 група)" description "Підгрупа МОН"
gam create group "class-10-v-info-g1@schoolgus.ukr.education" name "10-В клас Інформатика (1 група)" description "Підгрупа МОН"
gam create group "class-10-v-info-g2@schoolgus.ukr.education" name "10-В клас Інформатика (2 група)" description "Підгрупа МОН"
gam create group "class-10-v-tech-g1@schoolgus.ukr.education" name "10-В клас Трудове навчання (1 група)" description "Підгрупа МОН"
gam create group "class-10-v-tech-g2@schoolgus.ukr.education" name "10-В клас Трудове навчання (2 група)" description "Підгрупа МОН"
gam create group "class-10-g-ukr-g1@schoolgus.ukr.education" name "10-Г клас Українська мова (1 група)" description "Підгрупа МОН"
gam create group "class-10-g-ukr-g2@schoolgus.ukr.education" name "10-Г клас Українська мова (2 група)" description "Підгрупа МОН"
gam create group "class-10-g-eng-g1@schoolgus.ukr.education" name "10-Г клас Англійська мова (1 група)" description "Підгрупа МОН"
gam create group "class-10-g-eng-g2@schoolgus.ukr.education" name "10-Г клас Англійська мова (2 група)" description "Підгрупа МОН"
gam create group "class-10-g-info-g1@schoolgus.ukr.education" name "10-Г клас Інформатика (1 група)" description "Підгрупа МОН"
gam create group "class-10-g-info-g2@schoolgus.ukr.education" name "10-Г клас Інформатика (2 група)" description "Підгрупа МОН"
gam create group "class-10-g-tech-g1@schoolgus.ukr.education" name "10-Г клас Трудове навчання (1 група)" description "Підгрупа МОН"
gam create group "class-10-g-tech-g2@schoolgus.ukr.education" name "10-Г клас Трудове навчання (2 група)" description "Підгрупа МОН"
gam create group "class-11-a-ukr-g1@schoolgus.ukr.education" name "11-А клас Українська мова (1 група)" description "Підгрупа МОН"
gam create group "class-11-a-ukr-g2@schoolgus.ukr.education" name "11-А клас Українська мова (2 група)" description "Підгрупа МОН"
gam create group "class-11-a-eng-g1@schoolgus.ukr.education" name "11-А клас Англійська мова (1 група)" description "Підгрупа МОН"
gam create group "class-11-a-eng-g2@schoolgus.ukr.education" name "11-А клас Англійська мова (2 група)" description "Підгрупа МОН"
gam create group "class-11-a-info-g1@schoolgus.ukr.education" name "11-А клас Інформатика (1 група)" description "Підгрупа МОН"
gam create group "class-11-a-info-g2@schoolgus.ukr.education" name "11-А клас Інформатика (2 група)" description "Підгрупа МОН"
gam create group "class-11-a-tech-g1@schoolgus.ukr.education" name "11-А клас Трудове навчання (1 група)" description "Підгрупа МОН"
gam create group "class-11-a-tech-g2@schoolgus.ukr.education" name "11-А клас Трудове навчання (2 група)" description "Підгрупа МОН"
gam create group "class-11-b-ukr-g1@schoolgus.ukr.education" name "11-Б клас Українська мова (1 група)" description "Підгрупа МОН"
gam create group "class-11-b-ukr-g2@schoolgus.ukr.education" name "11-Б клас Українська мова (2 група)" description "Підгрупа МОН"
gam create group "class-11-b-eng-g1@schoolgus.ukr.education" name "11-Б клас Англійська мова (1 група)" description "Підгрупа МОН"
gam create group "class-11-b-eng-g2@schoolgus.ukr.education" name "11-Б клас Англійська мова (2 група)" description "Підгрупа МОН"
gam create group "class-11-b-info-g1@schoolgus.ukr.education" name "11-Б клас Інформатика (1 група)" description "Підгрупа МОН"
gam create group "class-11-b-info-g2@schoolgus.ukr.education" name "11-Б клас Інформатика (2 група)" description "Підгрупа МОН"
gam create group "class-11-b-tech-g1@schoolgus.ukr.education" name "11-Б клас Трудове навчання (1 група)" description "Підгрупа МОН"
gam create group "class-11-b-tech-g2@schoolgus.ukr.education" name "11-Б клас Трудове навчання (2 група)" description "Підгрупа МОН"
gam create group "class-11-v-ukr-g1@schoolgus.ukr.education" name "11-В клас Українська мова (1 група)" description "Підгрупа МОН"
gam create group "class-11-v-ukr-g2@schoolgus.ukr.education" name "11-В клас Українська мова (2 група)" description "Підгрупа МОН"
gam create group "class-11-v-eng-g1@schoolgus.ukr.education" name "11-В клас Англійська мова (1 група)" description "Підгрупа МОН"
gam create group "class-11-v-eng-g2@schoolgus.ukr.education" name "11-В клас Англійська мова (2 група)" description "Підгрупа МОН"
gam create group "class-11-v-info-g1@schoolgus.ukr.education" name "11-В клас Інформатика (1 група)" description "Підгрупа МОН"
gam create group "class-11-v-info-g2@schoolgus.ukr.education" name "11-В клас Інформатика (2 група)" description "Підгрупа МОН"
gam create group "class-11-v-tech-g1@schoolgus.ukr.education" name "11-В клас Трудове навчання (1 група)" description "Підгрупа МОН"
gam create group "class-11-v-tech-g2@schoolgus.ukr.education" name "11-В клас Трудове навчання (2 група)" description "Підгрупа МОН"
gam create group "class-11-g-ukr-g1@schoolgus.ukr.education" name "11-Г клас Українська мова (1 група)" description "Підгрупа МОН"
gam create group "class-11-g-ukr-g2@schoolgus.ukr.education" name "11-Г клас Українська мова (2 група)" description "Підгрупа МОН"
gam create group "class-11-g-eng-g1@schoolgus.ukr.education" name "11-Г клас Англійська мова (1 група)" description "Підгрупа МОН"
gam create group "class-11-g-eng-g2@schoolgus.ukr.education" name "11-Г клас Англійська мова (2 група)" description "Підгрупа МОН"
gam create group "class-11-g-info-g1@schoolgus.ukr.education" name "11-Г клас Інформатика (1 група)" description "Підгрупа МОН"
gam create group "class-11-g-info-g2@schoolgus.ukr.education" name "11-Г клас Інформатика (2 група)" description "Підгрупа МОН"
gam create group "class-11-g-tech-g1@schoolgus.ukr.education" name "11-Г клас Трудове навчання (1 група)" description "Підгрупа МОН"
gam create group "class-11-g-tech-g2@schoolgus.ukr.education" name "11-Г клас Трудове навчання (2 група)" description "Підгрупа МОН"
